# Form implementation generated from reading ui file 'C:\Users\lap\Documents\Autoclcicker\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 300)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.tabWidget.setStyleSheet("border-radius: 20px")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_8 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.tab_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_3.setStyleSheet("border: 3px solid rgba(0, 0, 0, 1);\n"
"font: 36pt \"Segoe UI\";\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 150, 50))
        self.label_2.setStyleSheet("border: 2px solid rgba(0, 0, 0, 1);\n"
"border-radius: 20px")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setGeometry(QtCore.QRect(20, 60, 100, 60))
        self.pushButton.setStyleSheet("background-color: rgba(170, 170, 255, 150);\n"
"border-radius: 15px;\n"
"font: 600 14pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 180, 100, 60))
        self.pushButton_2.setStyleSheet("background-color: rgba(170, 170, 255, 150);\n"
"border-radius: 15px;\n"
"font: 600 14pt \"Segoe UI\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(parent=self.tab)
        self.label_7.setGeometry(QtCore.QRect(150, 70, 241, 101))
        self.label_7.setStyleSheet("border: 3px solid rgba(0, 0, 0, 1);\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(parent=self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(330, 50, 50, 20))
        self.radioButton.setStyleSheet("")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.tab_2)
        self.radioButton_2.setGeometry(QtCore.QRect(330, 100, 50, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.tab_2)
        self.radioButton_3.setGeometry(QtCore.QRect(330, 150, 50, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_4 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 165, 40))
        self.label_4.setStyleSheet("border: 2px solid rgba(0, 0, 0, 1);")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(32, 50, 100, 30))
        self.lineEdit.setStyleSheet("border: 2px solid rgba(0, 0, 0, 1);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(0, 100, 170, 40))
        self.label_5.setStyleSheet("border: 2px solid rgba(0, 0, 0, 1);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(35, 140, 100, 30))
        self.lineEdit_2.setStyleSheet("border: 2px solid rgba(0, 0, 0, 1);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(150, 170, 241, 101))
        self.label_6.setStyleSheet("border: 3px solid rgba(0, 0, 0, 1);\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Выйти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Файл"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-style:italic;\">Status</span><span style=\" font-size:14pt;\">: </span><span style=\" font-size:14pt; font-weight:700; color:#ff0000;\">STOPED</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Информативное окно:</span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:700; font-style:italic;\">Горячая клавиша</span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:700; font-style:italic;\">по умолчанию </span><span style=\" font-size:11pt; font-weight:700; font-style:italic; text-decoration: underline;\">&quot;F8&quot;</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Autoclicker"))
        self.radioButton.setText(_translate("MainWindow", "ЛКМ"))
        self.radioButton_2.setText(_translate("MainWindow", "ПКМ"))
        self.radioButton_3.setText(_translate("MainWindow", "СКП"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">Скорость клик/сек</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">Горячая клавиша</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Информативное окно:</span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:700; font-style:italic;\">Горячая клавиша</span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:700; font-style:italic;\">по умолчанию </span><span style=\" font-size:11pt; font-weight:700; font-style:italic; text-decoration: underline;\">&quot;F8&quot;</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Setting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
